<b>Результат проверки загруженного теста: <?php echo $data['id']; ?></b><p>
Если в тесте имеются ошибки, его можно отредактировать, нажав кнопку снизу 
<a href='test_edit.php?id=<?php echo $data['id']; ?>'>Редактировать</a><p>

<div style='outline: 1px solid; text-align: left; overflow: auto; text-overflow: ellipsis;'>
<pre>
<?php echo $data['str']; ?>
</pre>
</div>

<div style='display: inline-block; background: #bbb; padding: 3px; outline: 1px solid;'>
<a href='test_edit.php?id=<?php echo $data['id']; ?>'>Редактировать</a>
</div>
<div style='display: inline-block; background: #bbb; padding: 3px; outline: 1px solid;'>
<a href='testlist.php'>Список тестов</a>
</div>
