<form action='uploadtest.php' enctype="multipart/form-data" method="POST">
Загрузка файла с тестом <b>№<?php echo $id; ?>: <?php echo $testname ?></b><p>

<input type=hidden name=id value=<?php echo $id; ?>>

<div class='border'>
<div style='padding: 10px;'>
<div>
<b>Кодировка исходного файла:</b>
</div>

<div style='display: inline-block; text-align: left;'>
<label><input type='radio' name='coding' value='UTF-8'>UTF-8</label></br>
<label><input type='radio' name='coding' value='Windows-1251' checked>Windows-1251</label>
</div>
<div>
<input type='file' name='userfile'>
<input type='submit' value='Загрузить'>
</div>
</div>
</div>
</form>
