<div style="float: left;">
<div style='display: inline-block; background: #fff; padding: 2px; outline: 1px solid;'><a href=index.php>home</a></div>
</div>

<div style="float: right;">

<?php
if (isset($_SESSION['login'])) {
    if ($_SESSION['login'] == 'admin') {
	echo "<div style='display: inline-block; background: #fff; padding: 2px; outline: 1px solid;'><a href='manual.php'>Формат файла с тестом</a></div>";
	echo "<div style='display: inline-block; background: #fff; padding: 2px; outline: 1px solid;'><a href='testlist.php'>Тесты</a></div>";
    }
?>
	<div style='display: inline-block; background: #fff; padding: 2px; outline: 1px solid;'>Вы вошли как: [<?php echo $_SESSION['username']; ?>] <a href=logout.php>Выйти</a></div>
<?php
}
else {
?>
	<div style='display: inline-block; background: #fff; padding: 2px; outline: 1px solid;'><a href=auth.php>войти</a></div> или <div style='display: inline-block; background: #fff; padding: 2px; outline: 1px solid;'><a href=register.php>зарегистрироваться</a></div>

<?php
}
?>

</div>
