<form>
<div>
Регистрация
</div>
<div style="display: inline-block; outline: solid 1px #16b1f8; background: #fff; box-shadow: 0 0 10px rgba(0,0,0,0.5);">
<div style='padding: 10px'>
    <table>
    <tr><td align='right'>Логин:</td><td><input type=text name=login required="required" id='login'></td><td><span id='lmess'></span></td></tr>
    <tr><td align='right'>Пароль:</td><td><input type=password name=pass1 required="required" id='p1'></td><td><span id='lp1'></span></td></tr>
    <tr><td align='right'>Повтор:</td><td><input type=password name=pass2 required="required" id='p2'></td><td><span id='lp2'></span></td></tr>
    <tr><td align='right'>E-mail:</td><td><input type=email name=email required="required"></td><td></td></tr>
    <tr><td align='right'>Фамилия И.О.:</td><td><input type=text name=fullname required="required"></td><td></td></tr>
    </table>
</div>
</div>
<div>
    <input type=submit value="Зарегистрироваться"></div>
</div>
</form>

<script type="text/javascript">
$('#login').blur(function() {
    $.ajax({
	type: 'POST',
	url: 'check_login.php',
	data: 'login='+$('#login').val(),
	success: function(data) {
	    $('#lmess').html(data);
	}
    });
});
$('#p1').blur(function() {
    var v1 = $('#p1').val();
    var v2 = $('#p2').val();
    if (v1 != '' && v2 != '' && v1 != v2) {
	$('#lp1').html('Пароли не совпадают');
	return false;
    }
});
$('#p2').blur(function() {
    var v1 = $('#p1').val();
    var v2 = $('#p2').val();
    if (v1 != '' && v2 != '' && v1 != v2) {
	$('#lp2').html('Пароли не совпадают');
	return false;
    }
});
</script>
