<!doctype html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Doctor</title>
    <link rel="stylesheet" href="styles.css" type="text/css">
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>

    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>

<?php
	include 'config/config.php';
	session_start();
?>

<body>

<article>
<main>
<header>
	<div class="authent">
		<?php include 'view/menu.phtml'; ?>
		<div style="padding: 10px; background: #f8f363; color: #16b1f8;">
			<h1>Ваш семейный доктор</h1>
			<h3>Доврачебное тестирование пациентов</h3>
		</div>
	</div>
</header>

<nav>
</nav>

<div style="background: #f8f7d7; padding: 20px;">
