<?php include 'top.phtml'; ?>

<b>Результат проверки загруженного теста: <?php echo $id; ?></b><p>

<div style='outline: 1px solid; text-align: left; overflow: auto; text-overflow: ellipsis;'>
<pre>
<?php echo $str; ?>
</pre>
</div>

<div style='display: inline-block; background: #bbb; padding: 3px; outline: 1px solid;'>
<a href='testlist.php'>Tests list</a>
</div>

<?php include 'footer.phtml'; ?>
